name: app_company
description: "Aplicación de gestión de créditos y cobranzas con Clean Architecture."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^1.2.2
  dartz: ^0.10.1
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
