export const PERMISSION_GROUP = {
  // ── IAM ──
  USERS: 'iam.users',
  ROLES: 'iam.roles',
  PERMISSIONS: 'iam.permissions',
  // ── ERP ──
  CATALOG: 'erp.catalog',
  PRODUCTS: 'erp.products',
  PRICE_LISTS: 'erp.price_lists',
  CUSTOMERS: 'erp.customers',
  SUPPLIERS: 'erp.suppliers',
  // Compras
  PURCHASE_REQUESTS: 'erp.purchase_requests',
  PURCHASE_ORDERS: 'erp.purchase_orders',
  PURCHASE_CONTRACTS: 'erp.purchase_contracts',
  // Ventas
  QUOTATIONS: 'erp.quotations',
  SALES_ORDERS: 'erp.sales_orders',
  COMMERCIAL_TERMS: 'erp.commercial_terms',
  SALES_COMMISSIONS: 'erp.sales_commissions',
  SALES_PRICE_LISTS: 'erp.sales_price_lists',
  // Inventario
  INVENTORY: 'erp.inventory',
  WAREHOUSES: 'erp.warehouses',
  TRANSFERS: 'erp.transfers',
  STOCK_ADJUSTMENTS: 'erp.stock_adjustments',
  PHYSICAL_COUNTS: 'erp.physical_counts',
  SERIAL_NUMBERS: 'erp.serial_numbers',
  STOCK_RESERVATIONS: 'erp.stock_reservations',
  // WMS
  WMS: 'wms',
  PACKING: 'wms.packing',
  SHIPPING: 'wms.shipping',
  RECEIVING: 'wms.receiving',
  // RRHH
  RRHH: 'rrhh',
  EMPLOYEES: 'rrhh.employees',
  PAYROLL: 'rrhh.payroll',
  ATTENDANCE: 'rrhh.attendance',
  // POS
  POS: 'pos',
  POS_OPEN: 'pos.open',
  POS_CLOSE: 'pos.close',
  POS_DISCOUNTS: 'pos.discounts',
  POS_VOID: 'pos.void',
  POS_RETURNS: 'pos.returns',
  // Configuración
  COMPANY_CONFIG: 'config.company',
  TAXES: 'config.taxes',
  CURRENCIES: 'config.currencies',
  UNITS_OF_MEASURE: 'config.units_of_measure',
  BRANDS: 'config.brands',
  CATEGORIES: 'config.categories',
} as const;

export const PERMISSION_ACTION = {
  VIEW: 'view',
  CREATE: 'create',
  EDIT: 'edit',
  DELETE: 'delete',
  APPROVE: 'approve',
  EXPORT: 'export',
  IMPORT: 'import',
  PRINT: 'print',
} as const;

export type PermissionGroup = (typeof PERMISSION_GROUP)[keyof typeof PERMISSION_GROUP];
export type PermissionAction = (typeof PERMISSION_ACTION)[keyof typeof PERMISSION_ACTION];

export function buildPermissionKey(group: PermissionGroup, action: PermissionAction): string {
  return `${group}.${action}`;
}

export const PERMISSIONS_LABELS: Record<string, string> = {
  'iam.users.view': 'Ver usuarios',
  'iam.users.create': 'Crear usuarios',
  'iam.users.edit': 'Editar usuarios',
  'iam.users.delete': 'Eliminar usuarios',
  'iam.roles.view': 'Ver roles',
  'iam.roles.create': 'Crear roles',
  'iam.roles.edit': 'Editar roles',
  'iam.roles.delete': 'Eliminar roles',
  'iam.permissions.view': 'Ver permisos',
  'iam.permissions.edit': 'Editar permisos',
  'erp.catalog.view': 'Ver catálogo',
  'erp.catalog.edit': 'Editar catálogo',
  'erp.products.view': 'Ver productos',
  'erp.products.create': 'Crear productos',
  'erp.products.edit': 'Editar productos',
  'erp.products.delete': 'Eliminar productos',
  'erp.products.export': 'Exportar productos',
  'erp.products.import': 'Importar productos',
  'erp.price_lists.view': 'Ver listas de precio',
  'erp.price_lists.edit': 'Editar listas de precio',
  'erp.customers.view': 'Ver clientes',
  'erp.customers.create': 'Crear clientes',
  'erp.customers.edit': 'Editar clientes',
  'erp.customers.delete': 'Eliminar clientes',
  'erp.suppliers.view': 'Ver proveedores',
  'erp.suppliers.create': 'Crear proveedores',
  'erp.suppliers.edit': 'Editar proveedores',
  'erp.suppliers.delete': 'Eliminar proveedores',
  'erp.purchase_requests.view': 'Ver solicitudes de compra',
  'erp.purchase_requests.create': 'Crear solicitudes de compra',
  'erp.purchase_requests.edit': 'Editar solicitudes de compra',
  'erp.purchase_requests.approve': 'Aprobar solicitudes de compra',
  'erp.purchase_orders.view': 'Ver órdenes de compra',
  'erp.purchase_orders.create': 'Crear órdenes de compra',
  'erp.purchase_orders.edit': 'Editar órdenes de compra',
  'erp.purchase_orders.approve': 'Aprobar órdenes de compra',
  'erp.purchase_orders.delete': 'Eliminar órdenes de compra',
  'erp.purchase_contracts.view': 'Ver contratos de compra',
  'erp.purchase_contracts.create': 'Crear contratos de compra',
  'erp.purchase_contracts.edit': 'Editar contratos de compra',
  'erp.quotations.view': 'Ver cotizaciones',
  'erp.quotations.create': 'Crear cotizaciones',
  'erp.quotations.edit': 'Editar cotizaciones',
  'erp.quotations.delete': 'Eliminar cotizaciones',
  'erp.sales_orders.view': 'Ver pedidos',
  'erp.sales_orders.create': 'Crear pedidos',
  'erp.sales_orders.edit': 'Editar pedidos',
  'erp.sales_orders.delete': 'Eliminar pedidos',
  'erp.sales_orders.print': 'Imprimir pedidos',
  'erp.inventory.view': 'Ver inventario',
  'erp.inventory.export': 'Exportar inventario',
  'erp.warehouses.view': 'Ver almacenes',
  'erp.warehouses.create': 'Crear almacenes',
  'erp.warehouses.edit': 'Editar almacenes',
  'erp.warehouses.delete': 'Eliminar almacenes',
  'erp.transfers.view': 'Ver transferencias',
  'erp.transfers.create': 'Crear transferencias',
  'erp.transfers.edit': 'Editar transferencias',
  'erp.transfers.approve': 'Aprobar transferencias',
  'erp.stock_adjustments.view': 'Ver ajustes',
  'erp.stock_adjustments.create': 'Crear ajustes',
  'erp.physical_counts.view': 'Ver conteos físicos',
  'erp.physical_counts.create': 'Crear conteos físicos',
  'erp.serial_numbers.view': 'Ver números de serie',
  'erp.serial_numbers.edit': 'Editar números de serie',
  'erp.stock_reservations.view': 'Ver reservas',
  'erp.stock_reservations.create': 'Crear reservas',
  'wms.view': 'Ver WMS',
  'wms.packing.view': 'Ver packing',
  'wms.packing.edit': 'Editar packing',
  'wms.shipping.view': 'Ver shipping',
  'wms.shipping.edit': 'Editar shipping',
  'wms.receiving.view': 'Ver receiving',
  'wms.receiving.edit': 'Editar receiving',
  'pos.open': 'Abrir POS',
  'pos.close': 'Cerrar POS',
  'pos.discounts': 'Descuentos en POS',
  'pos.void': 'Anular ventas POS',
  'pos.returns': 'Devoluciones POS',
  'config.company.view': 'Ver configuración',
  'config.company.edit': 'Editar configuración',
  'config.taxes.view': 'Ver impuestos',
  'config.taxes.edit': 'Editar impuestos',
};

export const PERMISSION_MODULES = [
  { key: PERMISSION_GROUP.USERS, label: 'Usuarios', icon: 'Users' },
  { key: PERMISSION_GROUP.ROLES, label: 'Roles', icon: 'Shield' },
  { key: PERMISSION_GROUP.CATALOG, label: 'Catálogo', icon: 'BookOpen' },
  { key: PERMISSION_GROUP.PRODUCTS, label: 'Productos', icon: 'Package' },
  { key: PERMISSION_GROUP.CUSTOMERS, label: 'Clientes', icon: 'Users' },
  { key: PERMISSION_GROUP.SUPPLIERS, label: 'Proveedores', icon: 'Truck' },
  { key: PERMISSION_GROUP.PURCHASE_REQUESTS, label: 'Solicitudes de Compra', icon: 'FileText' },
  { key: PERMISSION_GROUP.PURCHASE_ORDERS, label: 'Órdenes de Compra', icon: 'ShoppingCart' },
  { key: PERMISSION_GROUP.QUOTATIONS, label: 'Cotizaciones', icon: 'FileText' },
  { key: PERMISSION_GROUP.SALES_ORDERS, label: 'Pedidos', icon: 'ClipboardList' },
  { key: PERMISSION_GROUP.INVENTORY, label: 'Inventario', icon: 'Warehouse' },
  { key: PERMISSION_GROUP.WAREHOUSES, label: 'Almacenes', icon: 'Building2' },
  { key: PERMISSION_GROUP.TRANSFERS, label: 'Transferencias', icon: 'ArrowLeftRight' },
  { key: PERMISSION_GROUP.STOCK_ADJUSTMENTS, label: 'Ajustes de Stock', icon: 'Scale' },
  { key: PERMISSION_GROUP.PHYSICAL_COUNTS, label: 'Conteos Físicos', icon: 'ClipboardCheck' },
  { key: PERMISSION_GROUP.POS, label: 'Punto de Venta', icon: 'CreditCard' },
  { key: PERMISSION_GROUP.WMS, label: 'WMS', icon: 'PackageSearch' },
  { key: PERMISSION_GROUP.RRHH, label: 'RRHH', icon: 'Users' },
  { key: PERMISSION_GROUP.COMPANY_CONFIG, label: 'Configuración', icon: 'Settings' },
];

export const ACTIONS_BY_MODULE: Record<string, PermissionAction[]> = {
  [PERMISSION_GROUP.USERS]: ['view', 'create', 'edit', 'delete'],
  [PERMISSION_GROUP.ROLES]: ['view', 'create', 'edit', 'delete'],
  [PERMISSION_GROUP.CATALOG]: ['view', 'edit'],
  [PERMISSION_GROUP.PRODUCTS]: ['view', 'create', 'edit', 'delete', 'export', 'import'],
  [PERMISSION_GROUP.PRICE_LISTS]: ['view', 'edit'],
  [PERMISSION_GROUP.CUSTOMERS]: ['view', 'create', 'edit', 'delete'],
  [PERMISSION_GROUP.SUPPLIERS]: ['view', 'create', 'edit', 'delete'],
  [PERMISSION_GROUP.PURCHASE_REQUESTS]: ['view', 'create', 'edit', 'approve'],
  [PERMISSION_GROUP.PURCHASE_ORDERS]: ['view', 'create', 'edit', 'approve', 'delete'],
  [PERMISSION_GROUP.PURCHASE_CONTRACTS]: ['view', 'create', 'edit'],
  [PERMISSION_GROUP.QUOTATIONS]: ['view', 'create', 'edit', 'delete'],
  [PERMISSION_GROUP.SALES_ORDERS]: ['view', 'create', 'edit', 'delete', 'print'],
  [PERMISSION_GROUP.INVENTORY]: ['view', 'export'],
  [PERMISSION_GROUP.WAREHOUSES]: ['view', 'create', 'edit', 'delete'],
  [PERMISSION_GROUP.TRANSFERS]: ['view', 'create', 'edit', 'approve'],
  [PERMISSION_GROUP.STOCK_ADJUSTMENTS]: ['view', 'create'],
  [PERMISSION_GROUP.PHYSICAL_COUNTS]: ['view', 'create'],
  [PERMISSION_GROUP.SERIAL_NUMBERS]: ['view', 'edit'],
  [PERMISSION_GROUP.STOCK_RESERVATIONS]: ['view', 'create'],
  [PERMISSION_GROUP.WMS]: ['view'],
  [PERMISSION_GROUP.POS]: ['view', 'create', 'edit', 'delete'],
  [PERMISSION_GROUP.COMPANY_CONFIG]: ['view', 'edit'],
};
